ubuntu1;0.34;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image1.jpg
ubuntu2;0.46;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image1.jpg
ubuntu3;1.06;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image3.jpg
ubuntu4;2.91;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image2.jpg
ubuntu5;2.99;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/test_video3.mp4
ubuntu6;3.16;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/test_video3.mp4