ubuntu1;0.34;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image1.jpg
ubuntu2;0.46;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image2.jpg
ubuntu3;1.06;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image1.jpg
ubuntu4;2.91;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/test_video3.mp4
ubuntu5;2.99;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/test_video2.mp4
ubuntu6;3.16;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image3.jpg
ubuntu7;3.59;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image3.jpg
ubuntu8;4.01;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image1.jpg
ubuntu9;4.03;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image1.jpg
ubuntu10;4.64;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/test_video1.mp4
ubuntu11;4.72;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image2.jpg
ubuntu12;4.76;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/test_video3.mp4
ubuntu13;5.87;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/test_video2.mp4
ubuntu14;6.51;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image2.jpg
ubuntu15;6.57;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/test_video3.mp4
ubuntu16;7.1;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image3.jpg
ubuntu17;7.12;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/test_video3.mp4
ubuntu18;7.34;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image1.jpg
ubuntu19;7.4;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/test_video1.mp4
ubuntu20;7.79;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/test_image1.jpg
