ubuntu1;0.33;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu2;1.34;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu3;1.55;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu4;2.08;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu5;2.33;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu6;2.33;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu7;2.61;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu8;2.86;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu9;3.0;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu10;3.58;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu11;3.84;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu12;4.59;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu13;6.63;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu14;7.59;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu15;7.95;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu16;8.02;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu17;8.75;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu18;8.79;effect;python3 /home/ubuntu/python/effects.py {};/home/ubuntu/files/audio.wav
ubuntu19;9.55;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu20;10.29;effect;python3 /home/ubuntu/python/effects.py {};/home/ubuntu/files/audio.wav