ubuntu1;0.34;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu2;0.99;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu3;1.46;effect;python3 /home/ubuntu/python/effects.py {};/home/ubuntu/files/audio.wav
ubuntu4;4.69;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu5;5.21;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu6;5.22;effect;python3 /home/ubuntu/python/effects.py {};/home/ubuntu/files/audio.wav
ubuntu7;5.46;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu8;5.61;effect;python3 /home/ubuntu/python/effects.py {};/home/ubuntu/files/audio.wav
ubuntu9;6.53;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu10;6.63;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu11;6.86;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu12;7.34;effect;python3 /home/ubuntu/python/effects.py {};/home/ubuntu/files/audio.wav
ubuntu13;7.86;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu14;8.43;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu15;8.84;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu16;8.99;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu17;9.7;effect;python3 /home/ubuntu/python/effects.py {};/home/ubuntu/files/audio.wav
ubuntu18;10.05;effect;python3 /home/ubuntu/python/effects.py {};/home/ubuntu/files/audio.wav
ubuntu19;10.28;speech_recognition;python3 /home/ubuntu/python/speech_rec.py {};/home/ubuntu/files/podcast_3-4.wav
ubuntu20;10.31;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
