ubuntu1;0.05;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu2;0.07;effect;python3 /home/ubuntu/python/effects.py {};/home/ubuntu/files/audio.wav
ubuntu3;0.31;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu4;0.57;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu5;1.34;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu6;1.35;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu7;1.44;speech_recognition;python3 /home/ubuntu/python/speech_rec.py {};/home/ubuntu/files/podcast_3-4.wav
ubuntu8;1.45;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu9;1.56;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu10;1.73;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu11;4.66;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu12;4.89;effect;python3 /home/ubuntu/python/effects.py {};/home/ubuntu/files/audio.wav
ubuntu13;4.96;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu14;5.17;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu15;6.52;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu16;6.7;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu17;7.32;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu18;7.64;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu19;8.06;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu20;8.17;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
