ubuntu1;2.74;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu2;3.88;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu3;4.06;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu4;5.62;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu5;6.23;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu6;7.92;speech_recognition;python3 /home/ubuntu/python/speech_rec.py {};/home/ubuntu/files/podcast_3-4.wav
ubuntu7;8.36;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu8;8.67;speech_recognition;python3 /home/ubuntu/python/speech_rec.py {};/home/ubuntu/files/podcast_3-4.wav
ubuntu9;10.3;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu10;10.97;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu11;11.27;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu12;11.37;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu13;11.56;effect;python3 /home/ubuntu/python/effects.py {};/home/ubuntu/files/audio.wav
ubuntu14;11.95;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu15;12.46;speech_recognition;python3 /home/ubuntu/python/speech_rec.py {};/home/ubuntu/files/podcast_3-4.wav
ubuntu16;13.44;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu17;13.8;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu18;13.92;speech_recognition;python3 /home/ubuntu/python/speech_rec.py {};/home/ubuntu/files/podcast_3-4.wav
ubuntu19;14.51;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu20;14.54;speech_recognition;python3 /home/ubuntu/python/speech_rec.py {};/home/ubuntu/files/podcast_3-4.wav
