# container_name;launch_time;program_name;command_format;input_file
ubuntu1;0.0;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu2;0.1;blur;python3 /home/ubuntu/python/blur.py {} 30;/home/ubuntu/files/image.jpg
ubuntu3;0.2;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4
ubuntu4;0.3;resize;python3 /home/ubuntu/python/resize.py {};/home/ubuntu/files/video.mp4